# Generated by Django 3.2.25 on 2024-07-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Cliente')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email ')),
                ('state', models.CharField(max_length=20, null=True, verbose_name='Estado')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Cidade')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Endereço')),
                ('create_by', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'db_table': 'customers_customer',
            },
        ),
    ]
