# Generated by Django 3.2.25 on 2024-07-06 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('ncm', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='Ncm')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('stock', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(0)], verbose_name='Quantidade em estoque')),
                ('manufacturing_date', models.DateField()),
                ('create_by', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products_product',
            },
        ),
    ]
